### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by mitsuki808** [zybron/RPSBot#12]
Commands are not working on a server that the bot has just been added to.
![rps bot](https://user-images.githubusercontent.com/105186548/167335546-f0d716a0-ebd6-4fd5-a592-dcb509e33d00.png)

**Comment by zybron** [comment]
So this could be one of two things. It can take up to an hour for slash commands to propagate to a server after adding the bot. Or it could be an issue with the invite permissions. Could you post the link you used to invite the bot and where it came from, please?

**Comment by zybron** [comment]
I think I found an issue with the invite link included in the help message. It didn't have the proper scopes for slash commands. If you used that link, it has been updated. You will need to kick the bot and re-invite using the new link. It's posted below in case you need it. I'm going to close this issue, please re-open if you are still having issues.

https://discord.com/api/oauth2/authorize?client_id=537420362921803787&scope=bot+applications.commands&permissions=157696
